# Supported funding model platforms for SAI-MAI SuperLiquid.INC

github: [Doctor0Evil]      # Verified GitHub Sponsors-enabled username
patreon: Doctor0EvilLabs   # Verified Patreon username
open_collective: superliquid-inc # Verified Open Collective identity
ko_fi: Doctor0EvilLabs     # Verified Ko-fi username
tidelift: npm/superliquid-inc # Package name on Tidelift
community_bridge: superliquid-inc # Community Bridge project-name
liberapay: Doctor0Evil     # Liberapay username
issuehunt: Doctor0Evil     # IssueHunt username
lfx_crowdfunding: superliquid-inc # LFX Crowdfunding project-name
polar: Doctor0Evil         # Polar username
buy_me_a_coffee: Doctor0EvilLabs # Buy Me a Coffee username
thanks_dev: Doctor0Evil    # thanks.dev username
custom: ['https://superliquid.inc/support', 'https://github.com/Doctor0Evil/Sponsor']
