name: AI Governance Orchestration Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'  # daily midnight UTC run

jobs:
  orchestration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Identity Authentication Tests
        run: |
          echo "Running identity authentication particle tests..."
          pytest tests/identity_authentication_tests.py

      - name: Run Consent Management Tests
        run: |
          echo "Running consent management particle tests..."
          pytest tests/consent_management_tests.py

      - name: Run Audit Logging Tests
        run: |
          echo "Running audit logging particle tests..."
          pytest tests/audit_logging_tests.py

      - name: Deploy to Staging Environment
        run: |
          echo "Deploying updated particles to staging..."
          ./deploy/deploy_staging.sh

      - name: Notify Governance Board
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"text": "Orchestration workflow run completed successfully."}' \
          $GOV_BOARD_WEBHOOK
